# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createDockerContainer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateDockerDialog(object):
    def setupUi(self, CreateDockerDialog):
        CreateDockerDialog.setObjectName("CreateDockerDialog")
        CreateDockerDialog.resize(430, 168)
        self.groupBox = QtWidgets.QGroupBox(CreateDockerDialog)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 431, 171))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.ContainerNameLabel = QtWidgets.QLabel(self.groupBox)
        self.ContainerNameLabel.setGeometry(QtCore.QRect(10, 10, 111, 18))
        self.ContainerNameLabel.setObjectName("ContainerNameLabel")
        self.UsernameLabel = QtWidgets.QLabel(self.groupBox)
        self.UsernameLabel.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.PasswordLabel = QtWidgets.QLabel(self.groupBox)
        self.PasswordLabel.setGeometry(QtCore.QRect(10, 90, 81, 31))
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.CreateCButton = QtWidgets.QPushButton(self.groupBox)
        self.CreateCButton.setGeometry(QtCore.QRect(20, 130, 88, 34))
        self.CreateCButton.setObjectName("CreateCButton")
        self.CancelButton = QtWidgets.QPushButton(self.groupBox)
        self.CancelButton.setGeometry(QtCore.QRect(320, 130, 88, 34))
        self.CancelButton.setObjectName("CancelButton")
        self.ContainerNameInput = QtWidgets.QLineEdit(self.groupBox)
        self.ContainerNameInput.setGeometry(QtCore.QRect(120, 10, 201, 32))
        self.ContainerNameInput.setObjectName("ContainerNameInput")
        self.UsernameInput = QtWidgets.QLineEdit(self.groupBox)
        self.UsernameInput.setGeometry(QtCore.QRect(120, 50, 201, 32))
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(self.groupBox)
        self.PasswordInput.setGeometry(QtCore.QRect(120, 90, 201, 32))
        self.PasswordInput.setObjectName("PasswordInput")

        self.retranslateUi(CreateDockerDialog)
        QtCore.QMetaObject.connectSlotsByName(CreateDockerDialog)

    def retranslateUi(self, CreateDockerDialog):
        _translate = QtCore.QCoreApplication.translate
        CreateDockerDialog.setWindowTitle(_translate("CreateDockerDialog", "Create Docker Container"))
        self.ContainerNameLabel.setText(_translate("CreateDockerDialog", "Container Name"))
        self.UsernameLabel.setText(_translate("CreateDockerDialog", "Username"))
        self.PasswordLabel.setText(_translate("CreateDockerDialog", "Password"))
        self.CreateCButton.setText(_translate("CreateDockerDialog", "Create"))
        self.CancelButton.setText(_translate("CreateDockerDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateDockerDialog = QtWidgets.QDialog()
    ui = Ui_CreateDockerDialog()
    ui.setupUi(CreateDockerDialog)
    CreateDockerDialog.show()
    sys.exit(app.exec_())
