# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'currentContainerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_currentContainer(object):
    def setupUi(self, currentContainer):
        currentContainer.setObjectName("currentContainer")
        currentContainer.resize(455, 135)
        self.groupbox = QtWidgets.QGroupBox(currentContainer)
        self.groupbox.setGeometry(QtCore.QRect(-10, 0, 471, 141))
        self.groupbox.setTitle("")
        self.groupbox.setObjectName("groupbox")
        self.containerOptions = QtWidgets.QComboBox(self.groupbox)
        self.containerOptions.setGeometry(QtCore.QRect(150, 10, 221, 32))
        self.containerOptions.setObjectName("containerOptions")
        self.CCLabel = QtWidgets.QLabel(self.groupbox)
        self.CCLabel.setGeometry(QtCore.QRect(20, 10, 121, 31))
        self.CCLabel.setObjectName("CCLabel")
        self.CCOk = QtWidgets.QPushButton(self.groupbox)
        self.CCOk.setGeometry(QtCore.QRect(20, 100, 88, 34))
        self.CCOk.setObjectName("CCOk")
        self.CCCancel = QtWidgets.QPushButton(self.groupbox)
        self.CCCancel.setGeometry(QtCore.QRect(370, 100, 88, 34))
        self.CCCancel.setObjectName("CCCancel")

        self.retranslateUi(currentContainer)
        QtCore.QMetaObject.connectSlotsByName(currentContainer)

    def retranslateUi(self, currentContainer):
        _translate = QtCore.QCoreApplication.translate
        currentContainer.setWindowTitle(_translate("currentContainer", "Choose Container"))
        self.CCLabel.setText(_translate("currentContainer", "Current Container:"))
        self.CCOk.setText(_translate("currentContainer", "Ok"))
        self.CCCancel.setText(_translate("currentContainer", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    currentContainer = QtWidgets.QDialog()
    ui = Ui_currentContainer()
    ui.setupUi(currentContainer)
    currentContainer.show()
    sys.exit(app.exec_())
