# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warningDocker.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarningDocker(object):
    def setupUi(self, WarningDocker):
        WarningDocker.setObjectName("WarningDocker")
        WarningDocker.resize(443, 52)
        self.warning = QtWidgets.QLabel(WarningDocker)
        self.warning.setGeometry(QtCore.QRect(0, 10, 401, 31))
        self.warning.setObjectName("warning")
        self.ok = QtWidgets.QPushButton(WarningDocker)
        self.ok.setGeometry(QtCore.QRect(390, 10, 51, 31))
        self.ok.setObjectName("ok")

        self.retranslateUi(WarningDocker)
        QtCore.QMetaObject.connectSlotsByName(WarningDocker)

    def retranslateUi(self, WarningDocker):
        _translate = QtCore.QCoreApplication.translate
        WarningDocker.setWindowTitle(_translate("WarningDocker", "Warning"))
        self.warning.setText(_translate("WarningDocker", "Warning: No docker container found. Start or find on \"Docker\".  "))
        self.ok.setText(_translate("WarningDocker", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WarningDocker = QtWidgets.QDialog()
    ui = Ui_WarningDocker()
    ui.setupUi(WarningDocker)
    WarningDocker.show()
    sys.exit(app.exec_())
